"""
Legacy catalogs imported from baseline scripts.
"""

TABLES_NEED_COLUMN_CHECK = {
    "acquisition of subsidiary",
    "changes in owners’ equity",
    "finance lease liabilities",
    "finance lease tangible fixed assets",
    "investment property held for capital appreciation",
    "investment property held to earn rental",
    "long-term borrowings, bonds and financial lease liabilities",
    "long-term deferred expenses",
    "long-term prepaid expenses",
    "long-term provisions",
    "mature livestock producing periodic products",
    "movement in temporary differences during the period",
    "movement in temporary differences during the year",
    "others payable to the state",
    "others payable to the state – long-term",
    "short-term borrowings, bonds and finance lease liabilities",
    "short-term provisions",
    "tangible fixed assets",
    "taxes and others payable to state treasury",
    "taxes and others payable to the state",
    "taxes and others payable to the state – long-term",
    "taxes and others receivable from state treasury",
    "taxes and others receivable from the state",
    "taxes payable to the state",
    "taxes payable to the state – long-term",
    "taxes receivable from state treasury",
    "taxes receivable from the state",
    "intangible fixed assets",
    "chi phí trả trước dài hạn",
    "tài sản cố định hữu hình",
    "tài sản cố định vô hình",
    "taxes payable to state treasury",
    "thuế và các khoản phải nộp nhà nước",
    "borrowings",
    "borrowings, bonds and finance lease liabilities",
    "short-term borrowings",
    "long-term borrowings",
}

TABLES_NEED_CHECK_SEPARATELY = {
    "finance lease tangible fixed assets",
    "goodwill",
    "investment property held for capital appreciation",
    "investment property held to earn rental",
    "mature livestock producing periodic products",
    "tangible fixed assets",
    "intangible fixed assets",
    "tài sản cố định hữu hình",
    "tài sản cố định vô hình",
}

TABLES_WITHOUT_TOTAL = {
    "business costs by element",
    "production and business costs by elements",
    "fair values versus carrying amounts",
    "fees paid and payable to the auditors",
    "geographical segments",
    "interest rate risk",
    "non-cash investing activity",
    "non-cash investing activities",
    "non-cash investing and financing activities",
    "significant transactions with related parties",
    "significant transactions with related companies",
    "corresponding figures",
    "transaction value",
    "annual interest rate",
    "equivalent vnd'000",
    "number of shares",
    "transfer from long-term borrowings",
    "recognised in consolidated balance sheet",
    "recognised in consolidated statement of income",
    "recognised in consolidated income statement",
}

CROSS_CHECK_TABLES_FORM_1 = {
    "accounts receivable from customers",
    "accounts receivable from customers detailed by significant customer",
    "accounts receivable from customers detailed by significant customers",
    "receivables on construction contracts according to stages of completion",
    "payables on construction contracts according to stages of completion",
    "deferred tax assets and liabilities",
    "deferred tax assets",
    "deferred tax liabilities",
    "accrued expenses",
    "accrued expenses – short-term",
    "accrued expenses - short-term",
    "accrued expenses – long-term",
    "accrued expenses - long-term",
    "unearned revenue",
    "unearned revenue – short-term",
    "unearned revenue – long-term",
    "other payables",
    "other payables – short-term",
    "other payables – long-term",
    "long-term borrowings",
    "long-term borrowings, bonds and financial lease liabilities",
    "long-term bonds and financial lease liabilities",
    "long-term financial lease liabilities",
    "long-term bonds",
}

# Legacy main.py expansion: form 1A/1B are preserved explicitly for
# baseline-authoritative parity. Consumers may choose to use FORM_1 union or
# the split sets depending on rule family.
CROSS_CHECK_TABLES_FORM_1A = {
    "receivables on construction contracts according to stages of completion",
    "payables on construction contracts according to stages of completion",
    "deferred tax assets and liabilities",
    "deferred tax assets",
    "deferred tax liabilities",
    "recognised deferred tax assets and liabilities",
    "accounts payable to suppliers",
    "accounts payable to suppliers detailed by significant suppliers",
    "accounts payable to suppliers detailed by significant supplier",
    "accounts payable to suppliers classified by payment terms",
    "accrued expenses",
    "accrued expenses – short-term",
    "accrued expenses - short-term",
    "accrued expenses – long-term",
    "accrued expenses - long-term",
    "deferred revenue",
    "deferred revenue – short-term",
    "deferred revenue – long-term",
    "long-term deferred revenue",
    "other payables",
    "other payables – short-term",
    "other payables – long-term",
    "long-term borrowings",
    "long-term bonds and financial lease liabilities",
    "long-term financial lease liabilities",
    "long-term bonds",
}

CROSS_CHECK_TABLES_FORM_1B = {
    "cash",
    "cash and cash equivalents",
    "cash in banks",
}

CROSS_CHECK_TABLES_FORM_2 = {
    "biological assets – long-term, other than mature livestock producing periodic products",
    "biological assets – short-term",
    "revenue from sales of goods and provision of services",
    "revenue from sales of goods",
    "revenue from provision of services",
}

CROSS_CHECK_TABLES_FORM_3 = {
    "acquisition of subsidiary",
    "business segments",
    "investments",
    "trading securities",
    "held-to-maturity investments",
    "equity investments in other entities",
    "equity investments in other entity",
    "bad and doubtful debts",
    "shortage of assets awaiting resolution",
    "inventories",
    "long-term work in progress",
    "construction in progress",
    "biological assets – long-term, other than mature livestock producing periodic products",
    "biological assets – short-term",
    "accounts receivable from customers",
    "accounts receivable from customers detailed by significant customer",
    "accounts receivable from customers detailed by significant customers",
    "accounts receivable from customers classified by payment term",
    "other short-term receivables comprised:",
    "other long-term receivables comprised:",
    "other receivables",
    "other short-term receivables",
    "other long-term receivables",
    "receivables from bcc contracts under joint control",
    "long-term prepaid expenses",
    "long-term deferred expenses",
    "investment property held for capital appreciation",
    "accounts payable to suppliers",
    "accounts payable to suppliers detailed by significant suppliers",
    "accounts payable to suppliers detailed by significant supplier",
    "taxes and others payable to state treasury",
    "taxes and others receivable from state treasury",
    "taxes and others receivable from and payable to state treasury",
    "taxes receivable from state treasury",
    "taxes payable to state treasury",
    "taxes and others receivable from the state",
    "taxes receivable from the state",
    "taxes and others payable to the state",
    "taxes payable to the state",
    "others payable to the state",
    "taxes and others payable to the state – long-term",
    "taxes payable to the state – long-term",
    "others payable to the state – long-term",
    "short-term borrowings",
    "short-term borrowings, bonds and finance lease liabilities",
    "short-term bonds and finance lease liabilities",
    "short-term bonds",
    "convertible bonds",
    "preference shares",
    "provisions",
    "short-term provisions",
    "long-term provisions",
    "changes in owners’ equity",
    "share capital",
    "contributed capital",
}
